### ISSUE TITLE
Image 1 for README

### ISSUE THREAD

**Issue by tomkellog** [HPI-SWA-Teaching/SWT17-Project-08#31]
this is not an issue, but one misused to upload an image as a static file to GitHub as this seems to be a common way to go about this.
<img width="1627" alt="screen shot 2017-06-12 at 22 44 32" src="https://user-images.githubusercontent.com/9486619/27054536-8e151cbe-4fc1-11e7-84b3-dae4c9b4b825.png">

**Comment by jonashering** [comment]
![waexpose](https://user-images.githubusercontent.com/15236859/28661227-4b0bef3e-72b6-11e7-919f-e0f99490d8e4.png)
