### ISSUE TITLE
UiEventHandler not bundled

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Teaching/SWT17-Project-08#34]
Neither the baseline appears to pull in the dependency for the `UiEventHandler`, nor does the .sar from the provided release. This will cause an exception in `WADashboard>>initialize`.

**Comment by jonashering** [comment]
Thanks for your remark! Since the needed dependencies were all included in "our" SWT-Squeakimage, we didn't think of that. We now included the needed dependency (`github://hpi-swa/widgets:master/repository`) to our baseline -- which solved us another issue, too!!
