### ISSUE TITLE
Aligning overlaps DockingBar

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Teaching/SWT17-Project-08#35]
Aligned windows will overlap the dockingbar if they're any taller than the default (e.g. after changing font size for a HiDPI screen):

![screenshot from 2017-06-14 09-53-06](https://user-images.githubusercontent.com/4313751/27121433-9e6fd398-50e7-11e7-9ee3-dcd95de49545.png)

**Comment by jonashering** [comment]
Hi Tom! Thanks for your input! We didn't consider this might be an issue when implementing our alignment methods and thus always used the default value of 18px.

In the next release coming on Tuesday it'll already be fixed.
