### ISSUE TITLE
On dashboard enable navigation by key up and down

### ISSUE THREAD

**Issue by feeds** [HPI-SWA-Teaching/SWT17-Project-08#38]

**Comment by jonashering** [comment]
Thanks for your comment! We'll evaluate when to integrate this feature in a future release :)

**Comment by jonashering** [comment]
Starting with WA 3.4, we use the up/down keys to navigate through different pages in Exposé view. Since there are at max only 8 windows per page in Exposé view, we do not consider it necessary to find a way to accelerate cycling through these 8 windows.

However, we very much appreciate your input!
