### ISSUE TITLE
Reset automatically after install and open preferences.

### ISSUE THREAD

**Issue by tomkellog** [HPI-SWA-Teaching/SWT17-Project-08#47]
This is the code Erik sent us.

|preferenceBrowser|

"extract the needed files"
self fileInMonticelloZipVersionNamed:
    'WindowAcrobatics-Core.mcz'.

"reset the system"
WAHandler reset.

"open the preferences for the user"
(UserDialogBoxMorph
	confirm: 'Do you want to adjust your WindowAcrobatics preferences now?'
	title: 'WindowAcrobatics Installation')
ifTrue: [
	preferenceBrowser := PreferenceBrowser open.
	preferenceBrowser selectedCategoryIndex:
		(preferenceBrowser categoryList indexOf: #WindowAcrobatics)]

**Comment by tomkellog** [comment]
also automatically switch to WA category with designated method of same name

**Comment by jonashering** [comment]
Now supported
