### ISSUE TITLE
Hitting "Esc" does not close the exposé if Browser has keyboard-focus

### ISSUE THREAD

**Issue by numberpi** [HPI-SWA-Teaching/SWT17-Project-08#48]
Instead the menu opens:

![image](https://user-images.githubusercontent.com/4451364/27590598-7c6d00c8-5b4f-11e7-8315-f274e47e2671.png)

**Comment by jonashering** [comment]
Again, we tried to reproduce this bug on all Windows, MacOS and Linux systems. Unfortunately, we didn't succeed...
