### ISSUE TITLE
As an enthusiastic Squeak user IWLT select a window in expose view to exit expose view and focus on the selected window

### ISSUE THREAD

**Issue by znnr** [HPI-SWA-Teaching/SWT17-Project-08#5]
🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈🎈

**Comment by numberpi** [comment]
Which kind of focus do you mean?
Bringing a window to front is already working. Or do you mean keyboard focus?

**Comment by jonashering** [comment]
We considered "bringing to focus" to be "bringing a window to front". So, this issue should already be closed by now.
