### ISSUE TITLE
I installed the newly released version 3.3 and it crashed my image...

### ISSUE THREAD

**Issue by Blubl** [HPI-SWA-Teaching/SWT17-Project-08#63]
When I first tried to used your Tool with alt+w this happend
![grafik](https://user-images.githubusercontent.com/20095713/28157271-3f3e45d6-67b6-11e7-9d8f-d291650a261a.png)
this happens with every other shortcut too

and later when I pressed some other keys the image crashed completely..

**Comment by znnr** [comment]
Thanks for your feedback, we are fixing the issue right now and will upload the modified release shortly.

**Comment by znnr** [comment]
The fix is online, please download it via the same link.
