### ISSUE TITLE
[BUGREPORT] Compability with the newest Squeak version

### ISSUE THREAD

**Issue by TMUKingston** [HPI-SWA-Teaching/SWT17-Project-08#66]
You guys seem to overwrite a method from the PasteUpMorph `filterEvent:for:`, to catch the events.

In the newest squeak version, this method got updated. The installation of WA (3.3 in my case) basically reverts this change and leads to a highly unstable image (not being able to create halos, emergency debuggers out of nowhere, ...)

The manual fix was to copy your three lines, revert `filterEvent:for:` to the newest squeak version, and paste your lines back in (with adjusted variable names)

Can you fix this bug?

Erik Brendel

**Comment by jonashering** [comment]
Mhmm, that is definitely not good... Thank you for providing us with this valuable information! We'll try to find a solution for this issue later this week (after the exam ;)).

**Comment by MkuuWaUjinga** [comment]
Will be fixed in the new version. Unfortunately this will only work with the newest squeak version, so from the new release on no more downwards compatibility.
